name: Neovim Configuration Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Neovim Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Install dependencies
        run: |
          # Install common dependencies
          sudo apt-get install -y make rsync curl unzip git

          # Install language servers and tools that your config might need
          sudo apt-get install -y nodejs npm ripgrep fd-find
          sudo npm install -g tree-sitter-cli

      - name: Cache plugin data
        uses: actions/cache@v3
        with:
          path: |
            /tmp/nvim_test_data
            /tmp/nvim_test_cache
          key: ${{ runner.os }}-nvim-${{ hashFiles('**/lazy-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nvim-

      - name: Run tests
        run: |
          # Ensure test directories exist
          mkdir -p /tmp/nvim_test_data /tmp/nvim_test_cache /tmp/nvim_test_state

          # Run the full test suite
          make test-full

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: /tmp/nvim_test.log
          retention-days: 5
